spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/hanghae?serverTimezone=UTC&characterEncoding=UTF-8
    username: application
    password: 1234qwer

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework.data: DEBUG
    org.hibernate: DEBUG